table raw_sales
	lineageTag: b8c5cf5a-f8e7-4777-8047-830cccaf035a

	measure 'Total Sales' =
			
			SUM(raw_sales[sales_amount])
		lineageTag: 66172e73-761d-4cc0-aa2b-ce0546b8e7fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Sales' =
			
			[Total Sales]
		lineageTag: f452104a-6453-4a1a-8d9f-40b1f21c1bb6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Sales' =
			
			CALCULATE(
			    [Total Sales],
			    DATEADD(
			        Dim_Date[date],
			        -1,
			        MONTH
			    )
			)
		lineageTag: 58ad570b-2e93-4fee-ac52-db02c509bec0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth %' =
			
			VAR CurrentSales = [Total Sales]
			VAR PreviousSales =
			    CALCULATE(
			        [Total Sales],
			        DATEADD(Dim_Date[date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(
			        CurrentSales - PreviousSales,
			        PreviousSales
			    )
		lineageTag: 688a5ece-e7e4-4850-8c3d-37aa257ef892

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Running Total Sales' =
			
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALLSELECTED(Dim_Date[date]),
			        Dim_Date[date] <= MAX(Dim_Date[date])
			    )
			)
		lineageTag: fcdd2f94-9879-42ae-b25f-fc32cc92f023

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 712d0326-55ef-488d-846a-f3413bd5dbec
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 78416d6c-e8b9-4cfc-bcc4-59cf461b8633
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 9a130ca0-df16-41d3-8ae1-4674bf493ea4
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 00272c4d-ad36-47cc-a05e-e5d1a5fd1e02
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: b2d5c7bf-2edc-49b4-b52d-ab46626915db
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 7d5e8c5c-21e4-4ebd-bc07-821177b05f8e
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 5531ec3a-9ae7-478d-b3ff-86399f083312
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: e48d1106-d3d9-4dec-a1db-da45d05d4c94
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 2e6e90e9-7bd9-45d4-9802-617ab3f93ade
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition raw_sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Downloads\Business Intelligence_Lab\LAB MINI PROJECT\brewmetrics-bi\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

